name: build

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: 30 3 * * SAT

jobs:
  source:
    runs-on: ubuntu-latest
    outputs:
      id: ${{ steps.cache-id.output }}
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: false
    - name: cache
      id: cache-id
      run: |
        set -eux
        iree_commit=$(git ls-tree HEAD iree|awk '{print $1}')
        echo "submodule-$iree_commit" >> $GITHUB_OUTPUT
    - name: Cache source
      id: submodules
      uses: actions/cache@v4
      with:
        path: .git/modules
        key: ${{ steps.cache-id.outputs.id }}
    - name: submodules
      run: |
        make submodules

  build:
    runs-on: ubuntu-latest
    needs: [source]
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: false
    - uses: actions/cache/restore@v4
      id: submodules
      with:
        path: .git/modules
        key: ${{ needs.source.outputs.id }}
    - name: submodules
      run: |
        make submodules
    - name: devcontainer
      uses: ./.github/workflows/actions/devcontainer
      id: devcontainer
    - name: setup
      run: |
        echo 'EXEC=${{ steps.devcontainer.outputs.exec }}' >> $GITHUB_ENV
    - name: configure
      run: |
        ${{ env.EXEC }} make configure WITH_CLANG=1
    - name: cache
      id: cache-id
      run: |
        set -eux
        ${{ env.EXEC }} df -h
        df -h
        if [ "$(stat --format %d /mnt)" != "$(stat --format %d .)" ]; then
          df -h /mnt
          sudo mkdir /mnt/.cache
          sudo chown ${USER} /mnt/.cache
          mkdir .cache
          sudo mount --bind /mnt/.cache .cache
        fi
        iree_commit=$(git -C iree log -n 1 --format=%h)
        echo "id=${{ hashFiles( 'iree/WORKSPACE', 'iree/.bazel*', 'iree/*.bazelrc') }}" >> $GITHUB_OUTPUT
        echo "id1=$iree_commit" >> $GITHUB_OUTPUT
        echo "id2=${{ hashFiles( 'Makefile', '.github/workflows/build.yml' ) }}" >> $GITHUB_OUTPUT
    - name: Cache Bazel repo
      id: bazel-repo
      uses: actions/cache@v4
      with:
        path: .cache/bazel-repo
        key: bazel-repo-${{ steps.cache-id.outputs.id }}
    - name: Cache Bazel build
      id: bazel-cache
      uses: actions/cache@v4
      with:
        path: .cache/bazel-build
        key: bazel-build-${{ steps.cache-id.outputs.id }}-${{ steps.cache-id.outputs.id1}}-${{ steps.cache-id.outputs.id2}}
        restore-keys: |
          bazel-build-${{ steps.cache-id.outputs.id }}-${{ steps.cache-id.outputs.id1}}
          bazel-build-${{ steps.cache-id.outputs.id }}
    - name: fetch
      run: |
        ${{ env.EXEC }} make fetch
    - name: build
      run: |
        ${{ env.EXEC }} make build
    - name: run
      run: |
        ${{ env.EXEC }} make run
    - name: disk space
      run: |
        ${{ env.EXEC }} df -h
        df -h
        du -sh .cache/* hlo/
